### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by D1M1TR10S**
Adding "agent-based" to the intro in the readme so it's clear that this is implemented as an agent, not a skillset. Feel free to word it as you see fit. Just need to make it clear somehow.

### CODE REVIEW

**Review by Houndie — APPROVED** [review]

**Review by Johnson1s — COMMENTED** [review]
cdf64bf2abd9894e15790dc537d62bff1e33115a

**Comment by matejzvikl23** [comment]
> Adding "agent-based" to the intro in the readme so it's clear that this is implemented as an agent, not a skillset. Feel free to word it as you see fit. Just need to make it clear somehow.

**Comment by matejzvikl23** [comment]
> Adding "agent-based" to the intro in the readme so it's clear that this is implemented as an agent, not a skillset. Feel free to word it as you see fit. Just need to make it clear somehow.

**Review by matejzvikl23 — COMMENTED** [review]
bb

**Pull request merged**
