### PR TITLE
refactor: use `@copilot-extensions/preview-sdk`

### PR DESCRIPTION
**Pull request by gr2m**
This pull request

- adds a new dependency: `@copilot-extensions/preview-sdk`
- refactors existing code to be an ES Module. Unfortunately the `.js` extension is necessary for imports in ESM apps.
- removes the custom ceviry function and uses the SDK instead

The SDK will have to be a native ES Module. Octokit was updated to ESM across all its SDKs. So we should encourage integrators to build apps as ES Modules from the getgo if they want to take advantage of the new SDK and the latest @octokit

The only relevant change is 89233db03428b52ce64a6573880a59ef10f8099c, it shows the code that can be removed form the app.

### CODE REVIEW

**Comment by gr2m** [comment]
Hmm the dev server fails now, any idea?

```
$ npm run dev

> gh-models@1.0.0 dev
> nodemon src/index.ts

[nodemon] 3.1.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/index.ts`
TypeError: Unknown file extension ".ts" for /Users/gr2m/code/copilot-extensions/github-models-extension/src/index.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async ModuleLoader.load (node:internal/modules/esm/loader:553:7)
    at async ModuleLoader.moduleProvider (node:internal/modules/esm/loader:434:45)
    at async link (node:internal/modules/esm/module_job:87:21) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by JasonEtco** [comment]
>  Unfortunately the .js extension is necessary for imports in ESM apps.

I would expect the TS compiler to handle this for us? That's likely why the dev script is failing.

**Review by JasonEtco — APPROVED** [review]
Fixed it by moving to use `tsx` instead of `nodemon/ts-node`, which has better support for ESM out of the box. Starts up fine now.

**Comment by gr2m** [comment]
> I would expect the TS compiler to handle this for us?

It would need more than transpiling, because the underlying node code cannot import files without file extensions. The build step would take each relative import path and find out to which file it resolves, then dynamically add the file extension or `/index.js` in case of folders. It might be out of scope of TypeScript itself, but it sure feels odd to have `.js` extensions for `.ts` source files.

**Pull request merged**
